# Generated by Django 5.1.5 on 2026-02-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Student', max_length=100)),
                ('mode', models.CharField(choices=[('brain_dump', 'Mode 1 – Word Vomit / Brain Dump'), ('notes_quiz', 'Mode 2 – Notes Upload & Quiz')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mastery', 'Mastery Reached'), ('max_turns', 'Max Turns Reached'), ('opted_out', 'Student Opted Out')], default='active', max_length=20)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('correct_followups', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_concepts', models.JSONField(default=list)),
                ('identified_misconceptions', models.JSONField(default=list)),
                ('demonstrated_concepts', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard', models.CharField(help_text='Georgia standard tag, e.g. S7L2', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('expected_concepts', models.JSONField(default=list, help_text='List of concept strings students should know for this topic.')),
                ('common_misconceptions', models.JSONField(default=list, help_text='List of known misconceptions for this topic.')),
            ],
            options={
                'ordering': ['standard', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NoteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notes/')),
                ('extracted_text', models.TextField(blank=True, help_text='Plain text extracted from the PDF.')),
                ('extracted_concepts', models.JSONField(default=list, help_text='Concepts extracted from the notes by AI.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_upload', to='recall.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_misconception', models.BooleanField(default=False, help_text='True if this tag represents a common misconception rather than a correct concept.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_tags', to='recall.topic')),
            ],
            options={
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recall.topic'),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('prompt', models.TextField(help_text='The question or prompt shown to the student.')),
                ('student_response', models.TextField(blank=True, help_text='What the student typed.')),
                ('ai_feedback', models.JSONField(default=dict, help_text='Structured AI feedback: missing concepts, misconceptions, explanation, follow-up question.')),
                ('is_correct', models.BooleanField(blank=True, help_text="Whether the student's response was assessed as correct for this follow-up.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='recall.attempt')),
            ],
            options={
                'ordering': ['attempt', 'turn_number'],
                'unique_together': {('attempt', 'turn_number')},
            },
        ),
    ]
