# Generated by Django 5.1.5 on 2026-03-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='current_transfer_level',
            field=models.PositiveIntegerField(default=1, help_text='Current transfer level (1-4) for Mode 3.'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('brain_dump', 'Mode 1 – Word Vomit / Brain Dump'), ('notes_quiz', 'Mode 2 – Notes Upload & Quiz'), ('transfer', 'Mode 3 – Transfer Challenge')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransferAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_response', models.TextField()),
                ('transfer_outcome', models.CharField(choices=[('no_transfer', 'No Transfer — restated definition or guessed'), ('surface', 'Surface Transfer — used keywords but wrong mapping'), ('partial', 'Partial Transfer — correct mapping, incomplete reasoning'), ('structural', 'Structural Transfer — mapped deep structure correctly'), ('creative', 'Creative Transfer — novel insight beyond expected mappings')], default='no_transfer', max_length=20)),
                ('concept_mappings_detected', models.JSONField(default=list, help_text='Which concept→context mappings the student made.')),
                ('reasoning_chain', models.JSONField(default=list, help_text="AI's step-by-step analysis of the student's transfer reasoning.")),
                ('transfer_failure_type', models.CharField(choices=[('none', 'No failure'), ('fixation', 'Fixation — stuck on surface features'), ('encapsulation', "Encapsulation — can't see concept outside original context"), ('overgeneralization', 'Overgeneralization — applied concept incorrectly'), ('fragmentation', "Fragmentation — mapped some pieces but couldn't integrate"), ('inert_knowledge', "Inert Knowledge — knows it but didn't activate it")], default='none', max_length=25)),
                ('transfer_failure_diagnosis', models.TextField(blank=True, help_text='Human-readable explanation of why transfer failed.')),
                ('transfer_score', models.FloatField(default=0.0, help_text='0.0 to 1.0 score for this transfer attempt.')),
                ('scaffold_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_attempts', to='recall.attempt')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferScaffold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaffold_type', models.CharField(choices=[('analogy_prompt', 'Analogy Prompt'), ('structure_hint', 'Structure Hint'), ('constraint_removal', 'Constraint Removal'), ('bridging_context', 'Bridging Context'), ('explicit_mapping', 'Explicit Mapping')], max_length=30)),
                ('scaffold_text', models.TextField()),
                ('order', models.IntegerField()),
                ('student_response_after', models.TextField(blank=True, help_text='What the student wrote after receiving this scaffold.')),
                ('helped', models.BooleanField(blank=True, help_text='Did transfer improve after this scaffold?', null=True)),
                ('transfer_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaffolds', to='recall.transferattempt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransferScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_level', models.IntegerField(choices=[(1, 'Near Transfer'), (2, 'Moderate Transfer'), (3, 'Far Transfer'), (4, 'Creative Transfer')], help_text='1=Near, 2=Moderate, 3=Far, 4=Creative')),
                ('scenario_text', models.TextField(help_text='The novel context prompt — deliberately avoids domain jargon.')),
                ('domain_context', models.CharField(help_text="The novel domain: e.g. 'cooking', 'engineering', 'space exploration'.", max_length=100)),
                ('target_concepts', models.JSONField(default=list, help_text='Which expected concepts this scenario tests transfer of.')),
                ('expected_mappings', models.JSONField(default=list, help_text='Concept-to-context mappings the AI expects a successful transfer to include.')),
                ('surface_distractors', models.JSONField(default=list, help_text='Surface features a student might fixate on that are irrelevant.')),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_scenarios', to='recall.topic')),
            ],
            options={
                'ordering': ['transfer_level'],
            },
        ),
        migrations.AddField(
            model_name='transferattempt',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='recall.transferscenario'),
        ),
    ]
