# Generated by Django 5.1.5 on 2026-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0002_attempt_current_transfer_level_alter_attempt_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='concise_explanations',
            field=models.JSONField(default=list, help_text='Brief feedback statements that clarify misunderstandings in age-appropriate language.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='expected_reasoning_patterns',
            field=models.JSONField(default=list, help_text='Types of relationships, mechanisms, or explanations students should demonstrate.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='supportive_followup_prompts',
            field=models.JSONField(default=list, help_text='Teacher-defined adaptive questions to push students toward deeper reasoning.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='visual_support',
            field=models.ImageField(blank=True, help_text='Relevant diagram, model, or image aligned with instructional content.', null=True, upload_to='topic_visuals/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='visual_support_caption',
            field=models.CharField(blank=True, help_text='Caption describing the visual support image.', max_length=300),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('brain_dump', 'Mode 1 – Active Recall Reflection'), ('notes_quiz', 'Mode 2 – Notes Upload & Quiz'), ('transfer', 'Mode 3 – Transfer Challenge')], max_length=20),
        ),
    ]
