# Generated by Django 5.1.5 on 2026-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0003_topic_concise_explanations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='probed_concepts',
            field=models.JSONField(default=list, help_text='Concepts the student only demonstrated after a probing follow-up question (needed a nudge).'),
        ),
    ]
